// <auto-generated />
using EFCorePMC.FluentAPI.OnetoOneMapping;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCorePMC.DataAnnotation.OnetoOneMapping.Migrations
{
    [DbContext(typeof(FAPIOnetoOneDbContext))]
    [Migration("20201208153535_EFAPI_OnetoOne_InitialMigration")]
    partial class EFAPI_OnetoOne_InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EFCorePMC.FluentAPI.OnetoOneMapping.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("CustomerId")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("FirstName");

                    b.Property<int?>("Gender")
                        .HasColumnType("INT")
                        .HasColumnName("Gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("LastName");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("EFCorePMC.FluentAPI.OnetoOneMapping.Models.CustomerRequisite", b =>
                {
                    b.Property<int>("CustomerRequisiteId")
                        .HasColumnType("INT")
                        .HasColumnName("CustomerId");

                    b.Property<string>("IdProof")
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("IdProof");

                    b.Property<int?>("IdProofType")
                        .HasColumnType("INT")
                        .HasColumnName("IdProofType");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("MobileNum");

                    b.HasKey("CustomerRequisiteId");

                    b.ToTable("CustomerRequisite");
                });

            modelBuilder.Entity("EFCorePMC.FluentAPI.OnetoOneMapping.Models.CustomerRequisite", b =>
                {
                    b.HasOne("EFCorePMC.FluentAPI.OnetoOneMapping.Models.Customer", "Customer")
                        .WithOne("CustomerRequisites")
                        .HasForeignKey("EFCorePMC.FluentAPI.OnetoOneMapping.Models.CustomerRequisite", "CustomerRequisiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EFCorePMC.FluentAPI.OnetoOneMapping.Models.Customer", b =>
                {
                    b.Navigation("CustomerRequisites");
                });
#pragma warning restore 612, 618
        }
    }
}
